import { createApp } from "vue";
import naiveUi from "./core/importNaiveUi.js";
import { router } from "./router";
import store from "./store";
import svgIcon from "./plugins/icons/svgIcon.jsx";
import "./core/permission";
import "./style/index.scss";
import App from "./App.jsx";
const app = createApp(App);
naiveUi(app);
app.component("svg-icon", svgIcon);
app.use(router);
app.use(store);
app.component("");
app.mount("#app");
